#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export TOKENIZERS_PARALLELISM=false
export WANDB_MODE="${WANDB_MODE:-disabled}"

TORCHRUN="${TORCHRUN:-${HOME}/miniconda3/envs/icae_v2/bin/torchrun}"
NUM_GPUS="${NUM_GPUS:-1}"
SEED="${SEED:-42}"
BF16=True
ENCODER_LAST_HIDDEN_ONLY=True
REPORT_TO=none

MODEL_NAME="${MODEL_NAME:-meta-llama/Llama-3.2-1B-Instruct}"
COMPRESS_RATIO="${COMPRESS_RATIO:-32}"
COMPRESSOR_VERSION="${COMPRESSOR_VERSION:-context_adaptive_v1}"
BUDGET_MODE=strict_context
LEGACY_BUDGET_MODE=strict_context

QUERY_ATTENTION_MODE=dot
QUERY_MODE=multi_slot
DIVERSITY_MODE=attention
QUERY_SLOTS=8
RELEVANCE_DIM=256
QUERY_PHRASE_WIDTHS=(2 4)

CONTEXT_WINDOW_WIDTHS=(8 32)
BLOCK_WIDTH="${BLOCK_WIDTH:-128}"
BOUNDARY_MODE="${BOUNDARY_MODE:-semantic}"
CONTEXT_BUDGET_MODE="${CONTEXT_BUDGET_MODE:-adaptive}"
MERGE_MODE="${MERGE_MODE:-hybrid}"
NOVELTY_WEIGHT="${NOVELTY_WEIGHT:-0.5}"
BOUNDARY_RADIUS="${BOUNDARY_RADIUS:-0.25}"
ANCHOR_WEIGHT="${ANCHOR_WEIGHT:-0.35}"

TAG="${TAG:-${COMPRESSOR_VERSION}}"
OUTPUT_DIR="${OUTPUT_DIR:-${ROOT}/output/${TAG}/ratio_${COMPRESS_RATIO}}"
